V4.0.0
tuneinsight/lattigo pull request #230
Opened 2022-08-13 11:34 UTC by Pro7ech

2022-08-18 16:38 UTC, jrtroncoso approved these changes

2022-08-18 16:53 UTC, romainbou commented on README.md
> +Any other issue will be closed, and for this we recommend the use of GitHub discussions or other topic-specific forums instead.
```suggestion
Any other issue will be closed, and for this we recommend the use of [GitHub discussions](https://github.com/tuneinsight/lattigo/discussions) or other topic-specific forums instead.
```

2022-08-18 16:53 UTC, romainbou commented on README.md
>  Lattigo is licensed under the Apache 2.0 License. See LICENSE.
```suggestion
Lattigo is licensed under the Apache 2.0 License. See [LICENSE](https://github.com/tuneinsight/lattigo/blob/master/LICENSE).
```

2022-08-18 16:53 UTC, romainbou commented on README.md
> +Branches with the prefix `dev_` are branches in active development and will be frequently rebased.
```suggestion
Branches with the prefix `dev_` are branches in active development and will be frequently rebased. Hence, we don't recommend depending on them.
```

2022-08-18 23:29 UTC, jrtroncoso approved these changes

2022-08-19 20:13 UTC, ChristianMct requested changes

2022-08-19 20:13 UTC, ChristianMct commented on README.md
> +If you want to contribute to Lattigo or you have any questions or suggestions, do not hesitate to contact us at
Shouldn't questions and suggestions go on the public discussion by default ? Should we say "non-public inquires" or something like that ?

2022-08-19 20:13 UTC, ChristianMct commented on CHANGELOG.md
> +# [4.0.0]
Bumping the major version number requires package name change to `github.com/tuneinsight/lattigo/v4` (along with associated changes).

2022-09-27 10:07 UTC, jrtroncoso commented
Should (all or some of) the functions in bfv/utils and bgv/utils be moved to rlwe/utils and made generic? There's no specific BFV/BGV function there besides bgv.Norm and bfv.Noise, which are used for the same purpose while indeed assuming a non-generic ciphertext structure (this could be generalized, e.g., by specifying the noise scale and modulus as input) despite getting rlwe generic types as inputs. Also, errorStats is replicated in bgv/decryptor and in bfv/utils, but only called in tests from the Norm and Noise functions respectively. As this is where BGV is merged, this could be considered already here to homogenize the noise evaluation of integer-based encryptions. Alternatively, it could be added as a separate minor PR later on.

2022-09-27 11:42 UTC, Pro7ech commented
I'm actively working on moving a lot of generic function from all schemes to the rlwe package. If you are ok with it, we can delay it to one of the PR that will tackle theses changes.

2022-10-04 00:08 UTC, jrtroncoso requested changes
Comments:
- bgv/evaluator: Automorphism and AutomorphismHoisted lack documentation
- ckks/bootstrapping/bootstrap_bench_test: for consistency, rename "*Bootstrapp" to "*Bootstrap"

2022-10-04 08:08 UTC, jrtroncoso approved these changes

2022-10-04 09:07 UTC, ChristianMct approved these changes

2022-10-04 10:02 UTC, romainbou approved these changes

2022-10-04 11:59 UTC, merged